services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-gpt-bot
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
