services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-gpt-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=health_gpt
      - POSTGRES_PASSWORD=health_gpt_password
      - POSTGRES_DB=health_gpt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: health-gpt-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=health_gpt
      - POSTGRES_PASSWORD=health_gpt_password
      - POSTGRES_DB=health_gpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U health_gpt"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: