services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-gpt-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - health_gpt_data:/app/data

volumes:
  health_gpt_data:
    name: health_gpt_data