services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-gpt-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=redis_password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy

  # redis:
  #   image: redis:7
  #   container_name: health-gpt-redis
  #   restart: unless-stopped
  #   command: redis-server --requirepass redis_password
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  redis_data: