global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: health-gpt
    static_configs:
      - targets: ['bot:9090']  # Uses internal Docker network name