# Bot configuration example.
#
# Environment variables are supported using ${VAR_NAME} syntax.
# Example usage:
#   export BOT_TOKEN="your-telegram-bot-token"
#   export OPENAI_KEY="your-openai-api-key"
#   export PG_PASSWORD="your-database-password"

# Telegram bot settings.
telegram:
  token: ${BOT_TOKEN}
  debug: false

# Storage configuration.
storage:
  type: postgresql
  postgresql:
    host: localhost
    port: 5432
    user: health_gpt
    password: ${PG_PASSWORD}
    database: health_gpt
    ssl_mode: disable
    migration: true

# LLM provider settings.
llm:
  provider: chatgpt
  chatgpt:
    api_key: ${OPENAI_KEY}
    model: gpt-4o
    temperature: 0.1
    top_p: 1.0
    max_tokens: 2000
    socks_proxy: socks5://localhost:1080

# Alternative LLM configuration examples:
#
# Claude:
# llm:
#   provider: claude
#   claude:
#     api_key: ${CLAUDE_KEY}
#     model: claude-3-opus-20240229
#     temperature: 0.7
#     max_tokens: 2000
#
# DeepSeek:
# llm:
#   provider: deepseek
#   deepseek:
#     api_key: ${DEEPSEEK_KEY}
#     model: deepseek-chat
#     temperature: 0.7
#     max_tokens: 2000
#
# Alternative storage examples:
#
# File system:
# storage:
#   type: fs
#   filesystem:
#     path: ./data
#
# In-memory:
# storage:
#   type: in-memory